ARG version
FROM almalinux:${version:-8}
# ARG variable before FROM will not work after FROM
ARG COURSE
ARG TRAINER
ENV COURSE=${COUSRE}
ENV TRAINER=${TRAINER}
RUN echo "course is: ${COURSE}, trainer is: ${TRAINER}"
